/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-02-03 15:36:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.stocks.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class tCompanyLc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/resource.jsp", Long.valueOf(1485375411000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

	String basePath = request.getScheme() + "://" +request.getServerName() + ":" + request.getServerPort() + request.getContextPath();
	String path=request.getContextPath();

      out.write("\r\n");
      out.write("<!-- 公共资源CSS,JS  -->\r\n");
      out.write("<!--Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/base.css\">\r\n");
      out.write("<!-- ** Javascript ** -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/urls.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/base.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/YDataGrid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/turnDate.js\"></script>");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  a:link{color: #333;text-decoration: none;}\r\n");
      out.write("  a:hover {color:red;} /*悬浮（鼠标经过）时颜色*/\r\n");
      out.write(" </style>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/pcity.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    /* 查看交易记录 */\r\n");
      out.write("    function seeDeal(c){\r\n");
      out.write("    \twindow.open(\"");
      out.print(path);
      out.write("/tBuyData/list.shtml?gcode=\"+c)  \r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    /* 修改状态 */\r\n");
      out.write("    function changeState(c,d,e){\r\n");
      out.write("    \t$('#Idiv4_fm')[0].reset();\r\n");
      out.write("    \t$(\"#Idiv4_fm #id\").val(d);\r\n");
      out.write("    \t$(\"#Idiv4_fm #state\").val(c);\r\n");
      out.write("    \t$(\"#Idiv4_fm #title\").text(e);\r\n");
      out.write("    \t$(\"#Idiv4\").dialog('open');\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv4_sub(){\r\n");
      out.write("  \t\t   $.ajax({\r\n");
      out.write("                cache: true,\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url:\"");
      out.print(path);
      out.write("/tCompanyLc/updateForm.do\",\r\n");
      out.write("                data:$('#Idiv4_fm').serialize(),// 你的formid或者 { id: idIndex, name: nameIndex },//提交参数\r\n");
      out.write("                async: false,\r\n");
      out.write("               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("                error: function(request) {\r\n");
      out.write("                    alert(\"操作失败了！\");\r\n");
      out.write("                },\r\n");
      out.write("                //data没有指定json的话默认string\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                \tif(data.msg=='1'){\r\n");
      out.write("                \t\tjeecg.tCompanyLc.init();\r\n");
      out.write("                \t\t$(\"#Idiv4\").dialog('close');\r\n");
      out.write("                \t}else{\r\n");
      out.write("                \t\talert(\"修改状态失败！\");\r\n");
      out.write("                \t}\r\n");
      out.write("                }\r\n");
      out.write("   \t\t  });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("      /* 查看图片信息alt */\r\n");
      out.write("    function seePic(c,d){\r\n");
      out.write("    \t$('#Idiv5_fm')[0].reset();\r\n");
      out.write("    \t$(\"#Idiv5_fm #title\").text(d);\r\n");
      out.write("    \t$(\"#Idiv5_fm #min_pic\").attr('src',\"http://image.sinajs.cn/newchart/min/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #daily_pic\").attr('src',\"http://image.sinajs.cn/newchart/daily/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #weekly_pic\").attr('src',\"http://image.sinajs.cn/newchart/weekly/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #monthly_pic\").attr('src',\"http://image.sinajs.cn/newchart/monthly/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #min_pic\").attr('alt',\"http://image.sinajs.cn/newchart/min/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #daily_pic\").attr('alt',\"http://image.sinajs.cn/newchart/daily/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #weekly_pic\").attr('alt',\"http://image.sinajs.cn/newchart/weekly/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5_fm #monthly_pic\").attr('alt',\"http://image.sinajs.cn/newchart/monthly/n/\"+c+\".gif\");\r\n");
      out.write("    \t$(\"#Idiv5\").dialog('open');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function div1Open(){\r\n");
      out.write("    \t   $(\"#Idiv1_dl\").html(\"\");\r\n");
      out.write("  \t\t   $.ajax({\r\n");
      out.write("                cache: true,\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url:\"");
      out.print(path);
      out.write("/tBusinessPlate/dataAll.do\",\r\n");
      out.write("                // data:$('#fm').serialize(),你的formid或者 { id: idIndex, name: nameIndex },//提交参数\r\n");
      out.write("                async: false,\r\n");
      out.write("               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("                error: function(request) {\r\n");
      out.write("                    alert(\"操作失败了！\");\r\n");
      out.write("                },\r\n");
      out.write("                //data没有指定json的话默认string\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                \t//var dataJson = eval(\"(\" + data + \")\");  \r\n");
      out.write("                \tvar k=data.total;\r\n");
      out.write("                \tfor(var i=0;i<k;i++){\r\n");
      out.write("                \t\t$(\"#Idiv1_dl\").append(\"<dd style=\\\"width: 137px;background: url(");
      out.print(basePath);
      out.write("/images/stock/hq_gif.gif) repeat-y -168px 0;float: left;position: relative;\\\">\"\r\n");
      out.write("                \t\t+\"<a href=\\\"#\\\" style=\\\"padding-left: 15px;display: block;height: 24px;outline: none;margin: 0 1px;\\\" onclick=\\\"addIdiv1(\"+data.rows[i].id+\",'\"+data.rows[i].platename+\"')\\\">\"\r\n");
      out.write("                \t\t+data.rows[i].platename+\"</a></dd>\");\r\n");
      out.write("                \t}\r\n");
      out.write("                }\r\n");
      out.write("   \t\t  });\r\n");
      out.write("   \t\t$(\"#Idiv1 #bpnamee\").val($(\"#editForm #bpname\").val());//修改传值，新增为空\r\n");
      out.write("    \t$(\"#Idiv1\").dialog('open');\r\n");
      out.write("    }\r\n");
      out.write("    function addIdiv1(a,b){\r\n");
      out.write("   \t\t$(\"#editForm #bpid\").val(a);\r\n");
      out.write("   \t\t$(\"#editForm #bpname\").val(b);\r\n");
      out.write("   \t\t$(\"#Idiv1\").dialog('close');\r\n");
      out.write("   \t\t//$(\"#Idiv1 #bpnamee\").val(b);\r\n");
      out.write("    }\r\n");
      out.write(" /*    function Idiv1_sub(){\r\n");
      out.write("    \t$(\"#Idiv1 #bpnamee\").val(\"\");\r\n");
      out.write("    \t$(\"#Idiv1\").dialog('close');\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv1_rest(){\r\n");
      out.write("    \t$(\"#editForm #bpid\").val(\"\");\r\n");
      out.write("    \t$(\"#editForm #bpname\").val(\"\");\r\n");
      out.write("    \t$(\"#Idiv1 #bpnamee\").val(\"\");\r\n");
      out.write("    } */\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function div2Open(){\r\n");
      out.write("    \t   $(\"#Idiv2_dl\").html(\"\");\r\n");
      out.write("  \t\t   $.ajax({\r\n");
      out.write("                cache: true,\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url:\"");
      out.print(path);
      out.write("/tConceptPlate/dataAll.do\",\r\n");
      out.write("                async: false,\r\n");
      out.write("               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("                error: function(request) {\r\n");
      out.write("                    alert(\"操作失败了！\");\r\n");
      out.write("                },\r\n");
      out.write("                //data没有指定json的话默认string\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                \t//var dataJson = eval(\"(\" + data + \")\");  \r\n");
      out.write("                \tvar k=data.total;\r\n");
      out.write("                \tfor(var i=0;i<k;i++){\r\n");
      out.write("                \t\t$(\"#Idiv2_dl\").append(\"<dd style=\\\"width: 137px;background: url(");
      out.print(basePath);
      out.write("/images/stock/hq_gif.gif) repeat-y -168px 0;float: left;position: relative;\\\">\"\r\n");
      out.write("                \t\t+\"<a href=\\\"#\\\" style=\\\"padding-left: 15px;display: block;height: 24px;outline: none;margin: 0 1px;\\\" onclick=\\\"addIdiv2(\"+data.rows[i].id+\",'\"+data.rows[i].platename+\"')\\\">\"\r\n");
      out.write("                \t\t+data.rows[i].platename+\"</a></dd>\");\r\n");
      out.write("                \t}\r\n");
      out.write("                }\r\n");
      out.write("   \t\t  });\r\n");
      out.write("   \t\t$(\"#Idiv2 #cpnamese\").val($(\"#editForm #cpnames\").val());\r\n");
      out.write("    \t$(\"#Idiv2\").dialog('open');\r\n");
      out.write("    }\r\n");
      out.write("    function addIdiv2(a,b){\r\n");
      out.write("    \tvar a1=$(\"#editForm #cpids\").val();\r\n");
      out.write("    \tvar a2=$(\"#editForm #cpnames\").val();\r\n");
      out.write("    \tvar a3=$(\"#Idiv2 #cpnamese\").val();\r\n");
      out.write("    \tif(!a3){\r\n");
      out.write("    \t\t$(\"#editForm #cpids\").val(a);\r\n");
      out.write("   \t\t\t$(\"#editForm #cpnames\").val(b);\r\n");
      out.write("   \t\t\t$(\"#Idiv2 #cpnamese\").val(b);\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$(\"#editForm #cpids\").val(a1+\",\"+a);\r\n");
      out.write("   \t\t\t$(\"#editForm #cpnames\").val(a2+\",\"+b);\r\n");
      out.write("   \t\t\t$(\"#Idiv2 #cpnamese\").val(a2+\",\"+b);\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv2_sub(){\r\n");
      out.write("    \t$(\"#Idiv2 #cpnamese\").val(\"\");\r\n");
      out.write("    \t$(\"#Idiv2\").dialog('close');\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv2_rest(){\r\n");
      out.write("    \t$(\"#editForm #cpids\").val(\"\");\r\n");
      out.write("    \t$(\"#editForm #cpnames\").val(\"\");\r\n");
      out.write("    \t$(\"#Idiv2 #cpnamese\").val(\"\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function div3Open(){\r\n");
      out.write("    \t$(\"#Idiv3\").dialog('open');\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv3_sub(){\r\n");
      out.write("    \tif(!$(\"#Idiv3 #ddlProvince\").val()){\r\n");
      out.write("    \t\talert(\"请选择省份\");\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t}\r\n");
      out.write("    \tif(!$(\"#Idiv3 #ddlCity\").val()){\r\n");
      out.write("    \t\talert(\"请选择城市\");\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t$(\"#editForm #province\").val($(\"#Idiv3 #ddlProvince\").val());\r\n");
      out.write("    \t$(\"#editForm #city\").val($(\"#Idiv3 #ddlCity\").val());\r\n");
      out.write("    \t$(\"#Idiv3\").dialog('close');\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("  <body class=\"easyui-layout\">\r\n");
      out.write(" \t <!-- Search panel start -->\r\n");
      out.write(" \t <div class=\"ui-search-panel\" region=\"north\" style=\"height: 80px;\" title=\"过滤条件\" data-options=\"striped: true,collapsible:false,iconCls:'icon-search',border:false\" >  \r\n");
      out.write(" \t <div style=\"float:left\">\r\n");
      out.write(" \t <form id=\"searchForm\">\r\n");
      out.write("        <p class=\"ui-fields\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">股票名:</label><input name=\"gname\" class=\"easyui-box ui-text\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">股票代码:</label><input name=\"gcode\" class=\"easyui-box ui-text\" style=\"width:100px;\">\r\n");
      out.write("\t    </p>\r\n");
      out.write("\t    <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"float:left\">\r\n");
      out.write("      &emsp;<a href='#' class=\"easyui-linkbutton\" onclick=\"seePic('sh000001','上证线图')\">查看上证线图</a>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div> \r\n");
      out.write("     <!--  Search panel end -->\r\n");
      out.write("\r\n");
      out.write("     <!-- Data List -->\r\n");
      out.write("     <div region=\"center\" border=\"false\" >\r\n");
      out.write("     <table id=\"data-list\"></table>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t \r\n");
      out.write("     <!-- Edit Win&Form -->\r\n");
      out.write("     <div id=\"edit-win\" class=\"easyui-dialog\" title=\"公司小幅变动信息\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:600px;height:380px;\">  \r\n");
      out.write("     \t<form id=\"editForm\" class=\"ui-form\" method=\"post\">  \r\n");
      out.write("     \t\t <input class=\"hidden\" name=\"id\">\r\n");
      out.write("     \t\t <div class=\"ui-edit\">\r\n");
      out.write("\t\t     \t   <div class=\"ftitle\">公司小幅变动信息</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>股票名称</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"gname\" type=\"text\" maxlength=\"50\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写股票名称\">\r\n");
      out.write("\t\t\t\t\t\t<label>股票代码</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"gcode\" type=\"text\" maxlength=\"50\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写股票代码\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>总市值(千万)</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"totalmoney\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"\" missingMessage=\"请填写总市值\">\r\n");
      out.write("\t\t\t\t\t\t<label>流通市值(千万)</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"circulatemoney\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"\" missingMessage=\"请填写流通值\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>市净率(越小越好)</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"lyr\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\" missingMessage=\"请填写市净率（越小越好)\">\r\n");
      out.write("\t\t\t\t\t\t<label>市盈率TTM</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"ttm\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\" missingMessage=\"请填写市盈率TTM\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>证监会行业名</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"bpid\" name=\"bpid\" class=\"easyui-validatebox\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"bpname\" name=\"bpname\" type=\"text\" maxlength=\"\" class=\"easyui-validatebox\" readonly=\"readonly\" style=\"width:400px;\"><a href=\"#\" onclick=\"div1Open()\"/>选择</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>概念板名称集</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"cpids\" name=\"cpids\" class=\"easyui-validatebox\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"cpnames\" name=\"cpnames\" type=\"text\" maxlength=\"\" class=\"easyui-validatebox\"  style=\"width:400px;\" readonly=\"readonly\"><a href=\"#\" onclick=\"div2Open()\"/>选择</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>地域</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"province\" name=\"province\" type=\"text\" class=\"easyui-validatebox\" style=\"width:200px;\" readonly=\"readonly\" placeholder=\"省份\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"city\" name=\"city\" type=\"text\" class=\"easyui-validatebox\" style=\"width:200px;\" readonly=\"readonly\" placeholder=\"城市\"><a href=\"#\" onclick=\"div3Open()\"/>选择</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("     \t</form>\r\n");
      out.write("  \t </div>\r\n");
      out.write("  \t \r\n");
      out.write(" \t <!--弹出层开始单选-->\r\n");
      out.write("\t<div id=\"Idiv1\" class=\"easyui-dialog\" title=\"证监会行业\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:850px;height:510px;\">\r\n");
      out.write("\t     <dl id=\"Idiv1_dl\" style=\"width: 835px;/* background: url(http://www.sinaimg.cn/cj/subject/2009/0618/sd_rt.gif) repeat-y center right; border: 1px solid #c5c7d3;*/padding: 1px 0px 0;\">\r\n");
      out.write("\t     </dl>\r\n");
      out.write("\t    <!--  <div style=\"width:100%;\">\r\n");
      out.write("\t     <input type=\"text\" id=\"bpnamee\" style=\"width:600px;margin-left: 40px;margin-top: 10px;\"/>\r\n");
      out.write("\t     <input type=\"submit\" value=\"确定\" onclick=\"Idiv1_sub()\"/>\r\n");
      out.write("\t     <input type=\"submit\" value=\"重置\" onclick=\"Idiv1_rest()\"/>\r\n");
      out.write("\t \t </div> -->\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <!--结束-->\r\n");
      out.write("  \t \r\n");
      out.write(" \t <!--弹出层开始-->\r\n");
      out.write("\t<div id=\"Idiv2\" class=\"easyui-dialog\" title=\"概念板块\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:850px;height:510px;\">\r\n");
      out.write("\t     <dl id=\"Idiv2_dl\" style=\"width: 835px;padding: 1px 0px 0;\">\r\n");
      out.write("\t     </dl>\r\n");
      out.write("\t     <div style=\"width:100%;\">\r\n");
      out.write("\t     <input type=\"text\" id=\"cpnamese\" style=\"width:600px;margin-left: 40px;margin-top: 10px;\"/>\r\n");
      out.write("\t     <input type=\"submit\" value=\"确定\" onclick=\"Idiv2_sub()\"/>\r\n");
      out.write("\t     <input type=\"submit\" value=\"重置\" onclick=\"Idiv2_rest()\"/>\r\n");
      out.write("\t \t </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <!--结束-->\r\n");
      out.write("  \t \r\n");
      out.write(" \t <!--弹出层开始-->\r\n");
      out.write("\t<div id=\"Idiv3\" class=\"easyui-dialog\" title=\"地域\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:400px;height:100px;\">\r\n");
      out.write("\t\t按省份选择： \r\n");
      out.write("\t\t<select  name=\"ddlProvince\" id=\"ddlProvince\" onchange=\"selectMoreCity(this)\">\r\n");
      out.write("\t\t </select>&nbsp;&nbsp;\r\n");
      out.write("\t\t <select name=\"ddlCity\" id=\"ddlCity\">\r\n");
      out.write("\t\t  <option selected value=\"\">城市</option>\r\n");
      out.write("\t\t </select>&nbsp;&nbsp;\r\n");
      out.write("\t\t <input type=\"submit\" value=\"确定\" onclick=\"Idiv3_sub()\"/>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <script type=\"text/javascript\" language =\"javascript\">\r\n");
      out.write("        //BindProvince();//只初始化省份\r\n");
      out.write("         BindCity(\"杭州\");//初始化，并选中洛阳市和洛阳市所在的省\r\n");
      out.write("     </script>\r\n");
      out.write("\t <!--结束-->\r\n");
      out.write("\t \r\n");
      out.write("  \t  <!--弹出层开始-->\r\n");
      out.write("\t<div id=\"Idiv4\" class=\"easyui-dialog\" title=\"修改状态\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:200px;height:160px;\">\r\n");
      out.write("\t     <div style=\"width:60%;\" align=\"center\">\r\n");
      out.write("\t     <form id=\"Idiv4_fm\" method=\"post\">\r\n");
      out.write("\t     \t<h3 id=\"title\"></h3>\r\n");
      out.write("\t     \t <input id=\"id\" name=\"id\" type=\"hidden\"/>\r\n");
      out.write("\t\t     <select id=\"state\" name=\"state\" style=\"width:150px;\">\r\n");
      out.write("\t\t     \t<option value=\"1\">已买</option>\r\n");
      out.write("\t\t     \t<option value=\"2\">特别关注</option>\r\n");
      out.write("\t\t     \t<option value=\"3\">正常关注</option>\r\n");
      out.write("\t\t     \t<option value=\"6\">正常</option>\r\n");
      out.write("\t\t     \t<option value=\"7\">关闭</option>\r\n");
      out.write("\t\t     </select>\r\n");
      out.write("\t     </form>\r\n");
      out.write("\t     <br>\r\n");
      out.write("\t     <input type=\"submit\" value=\"保存\" onclick=\"Idiv4_sub()\"/>\r\n");
      out.write("\t \t </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <!--结束-->\r\n");
      out.write("\t \r\n");
      out.write("  \t  <!--弹出层开始-->\r\n");
      out.write("\t<div id=\"Idiv5\" class=\"easyui-dialog\" title=\"图片查看\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:600px;height:450px;\">\r\n");
      out.write("\t     <div style=\"width:100%;\" align=\"center\">\r\n");
      out.write("\t     <form id=\"Idiv5_fm\" method=\"post\">\r\n");
      out.write("\t     <h2 id=\"title\"></h2>\r\n");
      out.write("\t     <h4>分时线图</h4>\r\n");
      out.write("\t     <img id=\"min_pic\" alt=\"http://image.sinajs.cn/newchart/min/n/sh601006.gif\" src=\"http://image.sinajs.cn/newchart/min/n/sh601006.gif\" ></img>\r\n");
      out.write("\t     <hr>\r\n");
      out.write("\t     <h4>日K线图</h4>\r\n");
      out.write("\t     <img id=\"daily_pic\" alt=\"http://image.sinajs.cn/newchart/daily/n/sh601006.gif\" src=\"http://image.sinajs.cn/newchart/daily/n/sh601006.gif\" />\r\n");
      out.write("\t     <hr>\r\n");
      out.write("\t     <h4>周K线图</h4>\r\n");
      out.write("\t     <img id=\"weekly_pic\" alt=\"http://image.sinajs.cn/newchart/weekly/n/sh601006.gif\" src=\"http://image.sinajs.cn/newchart/weekly/n/sh601006.gif\" />\r\n");
      out.write("\t     <hr>\r\n");
      out.write("\t     <h4>月K线图</h4>\r\n");
      out.write("\t     <img id=\"monthly_pic\" alt=\"http://image.sinajs.cn/newchart/monthly/n/sh601006.gif\" src=\"http://image.sinajs.cn/newchart/monthly/n/sh601006.gif\" />\r\n");
      out.write("\t     </form>\r\n");
      out.write("\t     <br>\r\n");
      out.write("\t \t </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <!--结束-->\r\n");
      out.write("\t \r\n");
      out.write("  \t \r\n");
      out.write("  \t <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/view/stocks/company/page-tCompanyLc.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
