/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-01-25 21:09:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.stocks.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class tRegionPlate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/resource.jsp", Long.valueOf(1485375411000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

	String basePath = request.getScheme() + "://" +request.getServerName() + ":" + request.getServerPort() + request.getContextPath();
	String path=request.getContextPath();

      out.write("\r\n");
      out.write("<!-- 公共资源CSS,JS  -->\r\n");
      out.write("<!--Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/base.css\">\r\n");
      out.write("<!-- ** Javascript ** -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/urls.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/base.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/YDataGrid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/turnDate.js\"></script>");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"easyui-layout\">\r\n");
      out.write(" \t <!-- Search panel start -->\r\n");
      out.write(" \t <div class=\"ui-search-panel\" region=\"north\" style=\"height: 80px;\" title=\"过滤条件\" data-options=\"striped: true,collapsible:false,iconCls:'icon-search',border:false\" >  \r\n");
      out.write(" \t <form id=\"searchForm\">\r\n");
      out.write("        <p class=\"ui-fields\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">名称:</label><input name=\"aname\" class=\"easyui-box ui-text\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">ID:</label><input name=\"id\" class=\"easyui-box ui-text\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">父ID:</label><input name=\"pid\" class=\"easyui-box ui-text\" style=\"width:100px;\">\r\n");
      out.write("\t    </p>\r\n");
      out.write("\t    <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("      </form>  \r\n");
      out.write("     </div> \r\n");
      out.write("     <!--  Search panel end -->\r\n");
      out.write("\r\n");
      out.write("     <!-- Data List -->\r\n");
      out.write("     <div region=\"center\" border=\"false\" >\r\n");
      out.write("     <table id=\"data-list\"></table>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t \r\n");
      out.write("     <!-- Edit Win&Form -->\r\n");
      out.write("     <div id=\"edit-win\" class=\"easyui-dialog\" title=\"概念板块\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:400px;height:380px;\">  \r\n");
      out.write("     \t<form id=\"editForm\" class=\"ui-form\" method=\"post\">  \r\n");
      out.write("     \t\t <input class=\"hidden\" name=\"id\">\r\n");
      out.write("     \t\t <div class=\"ui-edit\">\r\n");
      out.write("\t\t     \t   <div class=\"ftitle\">概念板块</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>名称:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"aname\" type=\"text\" maxlength=\"50\" class=\"easyui-validatebox\" data-options=\"required:true\" style=\"width:250px;\" missingMessage=\"请填写名称\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>父ID:</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"pid\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"required:true\" style=\"width:250px;\" missingMessage=\"请填写父ID\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("     \t</form>\r\n");
      out.write("  \t </div>\r\n");
      out.write("  \t <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/view/stocks/company/page-tRegionPlate.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
