/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-03-12 17:45:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/home/apache-tomcat-9.0.0.M13/webapps2/ROOT/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/view/resource.jsp", Long.valueOf(1489340410000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1489340448000L));
    _jspx_dependants.put("jar:file:/home/apache-tomcat-9.0.0.M13/webapps2/ROOT/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>恭喜发财</title>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath();
	String path=request.getContextPath();//         /stock

      out.write("\r\n");
      out.write("<!-- 公共资源CSS,JS  -->\r\n");
      out.write("<!--Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/base.css\">\r\n");
      out.write("<!-- ** Javascript ** -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/urls.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/base.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/YDataGrid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/turnDate.js\"></script>");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/main.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/ux/main/main.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function startExe(c){\r\n");
      out.write("    \tvar strPath;\r\n");
      out.write("    \tif(c=='1'){\r\n");
      out.write("    \t\tstrPath=\"F:/EXE生成包/stockTool/stockToolQQ.exe\";\r\n");
      out.write("    \t}\r\n");
      out.write("\t\tvar objShell = new ActiveXObject(\"wscript.shell\"); \r\n");
      out.write("\t\tobjShell.Run(strPath); \r\n");
      out.write("\t\tobjShell = null; \r\n");
      out.write("\t} \r\n");
      out.write("\t//注意路径中必须使用/ ,而不能使用\\ \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"easyui-layout\">\r\n");
      out.write(" \t<div class=\"ui-header\" data-options=\"region:'north',split:true,border:false\" style=\"height:40px;overflow: hidden;\">\r\n");
      out.write(" \t<h1>JEECG-Mybatis 演示系统</h1>\r\n");
      out.write(" \t<div  class=\"ui-login\">\r\n");
      out.write(" \t\t<div class=\"ui-login-info\">\r\n");
      out.write("\t \t\t欢迎 <span class=\"orange\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> 第[<span class=\"orange\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.loginCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>]次登录 \r\n");
      out.write("\t \t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t \t\t<a class=\"modify-pwd-btn\"  href=\"javascript:void(0);\">修改密码</a> |\r\n");
      out.write(" \t\t\t<a class=\"logout-btn\" href=\"");
      out.print(basePath);
      out.write("/logout.shtml\">退出</a>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write(" \t</div>\r\n");
      out.write(" \t</div>\r\n");
      out.write("\t<!-- 树形菜单 -->\r\n");
      out.write("\t<div data-options=\"region:'west',split:true,title:'功能导航'\" style=\"width:200px;\">\r\n");
      out.write("\t\t<div id=\"tree-box\" class=\"easyui-accordion\" data-options=\"fit:true,border:false\">\r\n");
      out.write("\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /view/main/main.jsp(56,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("item");
        // /view/main/main.jsp(56,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t<div title=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("\t\t\t\t");
              //  c:forEach
              org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
              try {
                _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
                _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
                // /view/main/main.jsp(58,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_c_005fforEach_005f1.setVar("node");
                // /view/main/main.jsp(58,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.children}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
                  if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      out.write("\r\n");
                      out.write("\t\t\t\t<a class=\"menu-item\" href=\"");
                      out.print(basePath);
                      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${node.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                      out.write('"');
                      out.write('>');
                      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${node.text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                      out.write("</a>\r\n");
                      out.write("\t\t\t\t");
                      int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                  }
                  if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_c_005fforEach_005f1.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
              }
              out.write("\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'south',split:true,border:false\" style=\"height: 30px;overflow:hidden;\">\r\n");
      out.write("\t\t<div class=\"panel-header\" style=\"border: none;text-align: center;\" >CopyRight &copy; 2013 JEECG 版权所有. &nbsp;&nbsp;</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 中间内容页面 -->\r\n");
      out.write("\t<div data-options=\"region:'center'\" >\r\n");
      out.write("\t\t<div class=\"easyui-tabs\" id=\"tab-box\" data-options=\"fit:true,border:false\">\r\n");
      out.write("\t\t\t<div title=\"Welcome\" style=\"padding:20px;overflow:hidden;\"> \r\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t<h3>简要说明</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>打开EXE,IE下需要ActiveX开启。</li>\r\n");
      out.write("\t\t\t\t\t\t<li>火狐需要JAVA，开启JAVA：在地址栏输入： about:plugins, 然后会打开插件管理的界面，然后选择java的plugin启用</li>\r\n");
      out.write("\t\t\t\t\t\t<li> <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"startExe(1)\">打开exe</a></li>\r\n");
      out.write("\t\t\t\t\t    <li>信息披露：上海证券交易所<a href=\"http://www.sse.com.cn\" target=\"_blank\">www.sse.com.cn</a></li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=stockToolQQ5.exe\"  class=\"easyui-linkbutton\" >下载QQ5秒EXE软件</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=stockToolQQ10.exe\"  class=\"easyui-linkbutton\" >下载QQ10秒EXE软件</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=rKupdateMACD.xls\"  class=\"easyui-linkbutton\" >下载 日K里更新MACD等数据模板.xls(东财choice)</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=shCompany.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 上证A股SH公司信息.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=shCompany2.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 上证A股SH公司信息2.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=szCompany.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 深证A股SZ公司信息.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=szCompany2.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 深证A股SZ公司信息2.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=szCompany3.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 深证A股SZ公司信息3.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t<a href=\"");
      out.print(path);
      out.write("/fileDownload/downloadFile.do?fileName=szCompany4.xls\"  class=\"easyui-linkbutton\" >下载公司信息里 深证A股SZ公司信息4.xls</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t<h3>技术交流</h3>\r\n");
      out.write("\t\t\t\t\t<p>  &nbsp;&nbsp;恭喜发财</p>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://finance.sina.com.cn/stock/\" target=\"_blank\">新浪股票首页</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://data.eastmoney.com/stock/lhb.html\" target=\"_blank\">东方财富龙虎榜</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://data.10jqka.com.cn/market/longhu/\" target=\"_blank\">同花顺龙虎榜</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/lhb/index.phtml\" target=\"_blank\">新浪龙虎榜</a></li> \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  modify password start -->\r\n");
      out.write("\t<div id=\"modify-pwd-win\"  class=\"easyui-dialog\" buttons=\"#editPwdbtn\" title=\"修改用户密码\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:350px;height:200px;\">\r\n");
      out.write("\t\t<form id=\"pwdForm\" action=\"modifyPwd.do\" class=\"ui-form\" method=\"post\">\r\n");
      out.write("     \t\t <input class=\"hidden\" name=\"id\">\r\n");
      out.write("     \t\t <input class=\"hidden\" name=\"email\">\r\n");
      out.write("     \t\t <div class=\"ui-edit\">\r\n");
      out.write("\t           <div class=\"fitem\">  \r\n");
      out.write("\t              <label>旧密码:</label>  \r\n");
      out.write("\t              <input id=\"oldPwd\" name=\"oldPwd\" type=\"password\" class=\"easyui-validatebox\"  data-options=\"required:true\"/>\r\n");
      out.write("\t           </div>\r\n");
      out.write("\t            <div class=\"fitem\">  \r\n");
      out.write("\t               <label>新密码:</label>  \r\n");
      out.write("\t               <input id=\"newPwd\" name=\"newPwd\" type=\"password\" class=\"easyui-validatebox\" data-options=\"required:true\" />\r\n");
      out.write("\t           </div> \r\n");
      out.write("\t           <div class=\"fitem\">  \r\n");
      out.write("\t               <label>重复密码:</label>  \r\n");
      out.write("\t              <input id=\"rpwd\" name=\"rpwd\" type=\"password\" class=\"easyui-validatebox\"   required=\"required\" validType=\"equals['#newPwd']\" />\r\n");
      out.write("\t           </div> \r\n");
      out.write("\t         </div>\r\n");
      out.write("     \t </form>\r\n");
      out.write("     \t <div id=\"editPwdbtn\" class=\"dialog-button\" >  \r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" id=\"btn-pwd-submit\">Submit</a>  \r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" id=\"btn-pwd-close\">Close</a>  \r\n");
      out.write("         </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- modify password end  -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
