/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-04-20 16:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.stocks.datas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class tBuyData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/resource.jsp", Long.valueOf(1489340410000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath();
	String path=request.getContextPath();//         /stock

      out.write("\r\n");
      out.write("<!-- 公共资源CSS,JS  -->\r\n");
      out.write("<!--Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/base.css\">\r\n");
      out.write("<!-- ** Javascript ** -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/urls.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/base.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/YDataGrid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/turnDate.js\"></script>");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function restSearch(){\r\n");
      out.write("    \t$(\"#searchForm\")[0].reset();\r\n");
      out.write("    }\r\n");
      out.write("    function changeGname(c){\r\n");
      out.write("   \t   if(c&&c.length==8){\r\n");
      out.write("   \t   \t\tvar t=c.substring(0,5);\r\n");
      out.write("   \t   \t\tif(t=='sz300'){\r\n");
      out.write("   \t   \t\t\t$(\"#editForm #gtype\").val(\"3\");\r\n");
      out.write("   \t   \t\t}else{\r\n");
      out.write("   \t   \t\t\tt=t.substring(0,2);\r\n");
      out.write("   \t   \t\t\tif(t=='sh'){\r\n");
      out.write("   \t   \t\t\t\t$(\"#editForm #gtype\").val(\"1\");\r\n");
      out.write("   \t   \t\t\t}else if(t=='sz'){\r\n");
      out.write("   \t   \t\t\t\t$(\"#editForm #gtype\").val(\"2\");\r\n");
      out.write("   \t   \t\t\t}else{\r\n");
      out.write("   \t   \t\t\t\talert(\"请输入正确的股票代码如：sh600000\")\r\n");
      out.write("    \t\t\t\t$(\"#editForm #gcode\").val(\"\");\r\n");
      out.write("    \t\t\t\treturn false;\r\n");
      out.write("   \t   \t\t\t}\r\n");
      out.write("   \t   \t\t}\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t                cache: true,\r\n");
      out.write("\t                type: \"POST\",\r\n");
      out.write("\t                url:\"");
      out.print(path);
      out.write("/tCompany/getGnameByGcode.do?gcode=\"+c,\r\n");
      out.write("\t                async: false,\r\n");
      out.write("\t               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("\t                error: function(request) {\r\n");
      out.write("\t                    alert(\"操作失败了！\");\r\n");
      out.write("\t                },\r\n");
      out.write("\t                //data没有指定json的话默认string\r\n");
      out.write("\t                success: function(data) {\r\n");
      out.write("                \t\t$(\"#editForm #gname\").val(data);\r\n");
      out.write("               \t\t }\r\n");
      out.write("\t   \t\t  });\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\talert(\"请输入正确的股票代码如：sh600000\")\r\n");
      out.write("    \t\t$(\"#editForm #gcode\").val(\"\");\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    function changeGainmoney(){\r\n");
      out.write("    \tif($(\"#editForm #sellmoney\").val()&&$(\"#editForm #totalmoney\").val()){\r\n");
      out.write("    \t\tvar c=parseFloat($(\"#editForm #sellmoney\").val())-parseFloat($(\"#editForm #totalmoney\").val());\r\n");
      out.write("    \t\t$(\"#editForm #gainmoney\").val(c.toFixed(2));\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\talert(\"请填写买入和卖出数据！\");\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"easyui-layout\">\r\n");
      out.write(" \t <!-- Search panel start -->\r\n");
      out.write(" \t <div class=\"ui-search-panel\" region=\"north\" style=\"height: 80px;\" title=\"过滤条件\" data-options=\"striped: true,collapsible:false,iconCls:'icon-search',border:false\" >  \r\n");
      out.write(" \t <div style=\"float:left\">\r\n");
      out.write(" \t <form id=\"searchForm\">\r\n");
      out.write("        <p class=\"ui-fields\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">股票代码:</label><input name=\"gcode\" class=\"easyui-box ui-text\" style=\"width:80px;\">\r\n");
      out.write("\t\t\t<label>股票类型:</label>\r\n");
      out.write("\t\t\t<select name=\"gtype\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">上证股sh</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">深圳股sz</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">创业板sz300</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label class=\"ui-label\">证券公司:</label>\r\n");
      out.write("\t\t\t<select name=\"securitycompany\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">财通证券</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label>年份:</label>\r\n");
      out.write("\t\t\t<input name=\"buyyear\" type=\"text\" maxlength=\"4\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t<label>月份:</label>\r\n");
      out.write("\t\t\t<input name=\"buymonth\" type=\"text\" maxlength=\"2\" style=\"width:25px;\">\r\n");
      out.write("\t\t\t<label>单次盈利:</label>\r\n");
      out.write("\t\t\t<select name=\"gainmoneyorder\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label>单股总盈利:</label><!-- (注意：单次盈利有排序则总盈利和和总次数排序无效) -->\r\n");
      out.write("\t\t\t<select name=\"summoneyorder\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label>单股总次数:</label>\r\n");
      out.write("\t\t\t<select name=\"countnumorder\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t    </p>\r\n");
      out.write("\t    <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("      </form> \r\n");
      out.write("      </div> \r\n");
      out.write("       <div style=\"float:left\">\r\n");
      out.write("      \t&emsp;<a href=\"#\"  class=\"easyui-linkbutton\" onclick=\"restSearch()\">重置</a>&emsp;\r\n");
      out.write("      </div>\r\n");
      out.write("     </div> \r\n");
      out.write("     <!--  Search panel end -->\r\n");
      out.write("\r\n");
      out.write("     <!-- Data List -->\r\n");
      out.write("     <div region=\"center\" border=\"false\" >\r\n");
      out.write("     <table id=\"data-list\"></table>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t \r\n");
      out.write("     <!-- Edit Win&Form -->\r\n");
      out.write("     <div id=\"edit-win\" class=\"easyui-dialog\" title=\"Basic window\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:400px;height:470px;\">  \r\n");
      out.write("     \t<form id=\"editForm\" class=\"ui-form\" method=\"post\">  \r\n");
      out.write("     \t\t <input class=\"hidden\" name=\"id\">\r\n");
      out.write("     \t\t <div class=\"ui-edit\">\r\n");
      out.write("\t\t     \t   <div class=\"ftitle\">购买数据</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>股票代码</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"gcode\" type=\"text\" maxlength=\"10\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写股票代码\" onblur=\"changeGname(this.value)\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>股票名称</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"gname\" name=\"gname\" type=\"text\" maxlength=\"10\" class=\"easyui-validatebox\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>股票类型</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"gtype\" name=\"gtype\" style=\"width:145px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">上证股sh</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">深圳股sz</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">创业板sz300</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>证券公司</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"securitycompany\" style=\"width:145px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">财通证券</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>账户</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"account\" style=\"width:145px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"27053782\">27053782</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>购买数量/手</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"num\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" precision=\"0\" min=\"0\" data-options=\"required:true\" missingMessage=\"请填写购买数量\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>购买总金额/元</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"totalmoney\" name=\"totalmoney\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"min:0,max:999999999,precision:2,required:true\" missingMessage=\"请填写购买总金额\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>卖出总金额/元</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"sellmoney\" name=\"sellmoney\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"min:0,max:999999999,precision:2\" onblur=\"changeGainmoney()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>盈利/元</label>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"gainmoney\" name=\"gainmoney\" type=\"text\" maxlength=\"\" class=\"easyui-validatebox\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>购买时间</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"buydate\" type=\"text\" maxlength=\"\" class=\"easyui-datetimebox\" data-options=\"required:true\" missingMessage=\"请填写购买时间\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>结束时间</label>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"enddate\" type=\"text\" maxlength=\"\" class=\"easyui-datetimebox\" data-options=\"\" missingMessage=\"请填写购买时间\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fitem\">\r\n");
      out.write("\t\t\t\t\t\t<label>购买状态</label>\r\n");
      out.write("\t     \t\t \t  \t<select name=\"state\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">进行中</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">已结束</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("     \t</form>\r\n");
      out.write("  \t </div>\r\n");
      out.write("  \t <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/view/stocks/datas/page-tBuyData.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
