/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-03-13 04:01:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.stocks.datas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class tDayBigdata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/resource.jsp", Long.valueOf(1489340410000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath();
	String path=request.getContextPath();//         /stock

      out.write("\r\n");
      out.write("<!-- 公共资源CSS,JS  -->\r\n");
      out.write("<!--Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/bootstrap/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/css/base.css\">\r\n");
      out.write("<!-- ** Javascript ** -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/urls.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/base.js?v=11\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/commons/YDataGrid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.3.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/stock/turnDate.js\"></script>");
      out.write("\r\n");
      out.write("     <style type=\"text/css\">\r\n");
      out.write("   #Idiv1_table tr td{\r\n");
      out.write("   \t\twidth:200px;height:25px;\r\n");
      out.write("   }\r\n");
      out.write("   </style>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t $(\"#Idiv1\").dialog({\r\n");
      out.write("           /*  resizable: false,\r\n");
      out.write("            height: \"auto\",\r\n");
      out.write("            width: 400,\r\n");
      out.write("            modal: true, */\r\n");
      out.write("            buttons:[\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\ttext:'确定',\r\n");
      out.write("\t\t\t\t\t\t\t\thandler:function (){Idiv1_sub()}\r\n");
      out.write("\t\t\t\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\t\t\t\ttext:'重置',\r\n");
      out.write("\t\t\t\t\t\t\t\thandler:function (){Idiv1_rest()}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t/* ,{\r\n");
      out.write("\t\t\t\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\t\t\t\thandler:function (){$(\"#Idiv2\").dialog(\"close\");}\r\n");
      out.write("\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t]\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("       function backBigDate(c){\r\n");
      out.write("  \t\t   $.ajax({\r\n");
      out.write("                cache: true,\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url:\"");
      out.print(path);
      out.write("/tDayBigdata/backDayBigdate.do?flag=\"+c,\r\n");
      out.write("                // data:$('#fm').serialize(),你的formid或者 { id: idIndex, name: nameIndex },//提交参数\r\n");
      out.write("                async: false,\r\n");
      out.write("               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("                error: function(request) {\r\n");
      out.write("                    alert(\"操作失败了！\");\r\n");
      out.write("                },\r\n");
      out.write("                //data没有指定json的话默认string\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                \tvar flag =data.msg;  \r\n");
      out.write("                \tif(flag=='1'){\r\n");
      out.write("                \t\tjeecg.tDayBigdata.init();\r\n");
      out.write("                \t}else if(flag=='2'){\r\n");
      out.write("                \t\tif(confirm('是否替换原先数据?')) \r\n");
      out.write("\t\t\t\t\t     { \r\n");
      out.write("\t\t\t\t\t         backDate('1');\r\n");
      out.write("\t\t\t\t\t         return true; \r\n");
      out.write("\t\t\t\t\t     }\r\n");
      out.write("\t\t\t\t\t     return false; \r\n");
      out.write("                \t}\r\n");
      out.write("                \t//var dataJson = eval(\"(\" + data + \")\");  \r\n");
      out.write("                }\r\n");
      out.write("   \t\t  });\r\n");
      out.write("    }\r\n");
      out.write("    function IdivOpen(c,d){\r\n");
      out.write("    \tif(d=='1'){\r\n");
      out.write("    \t\t$(\"#Idiv\"+c).dialog('open');\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$(\"#Idiv\"+c).dialog('close');\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv1_sub(){\r\n");
      out.write("\t\t$(\"#searchForm #increpermin\").val($(\"#Idiv1_form #increpermin\").val());\r\n");
      out.write("\t\t$(\"#searchForm #increpermax\").val($(\"#Idiv1_form #increpermax\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #increperorder\").val($(\"#Idiv1_form #increperorder\").val());\r\n");
      out.write("\t\t$(\"#searchForm #swingmin\").val($(\"#Idiv1_form #swingmin\").val());\r\n");
      out.write("\t\t$(\"#searchForm #swingmax\").val($(\"#Idiv1_form #swingmax\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #swingorder\").val($(\"#Idiv1_form #swingorder\").val());\r\n");
      out.write("\t\t$(\"#searchForm #tranumbermin\").val($(\"#Idiv1_form #tranumbermin\").val());\r\n");
      out.write("\t\t$(\"#searchForm #tranumbermax\").val($(\"#Idiv1_form #tranumbermax\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #tranumberorder\").val($(\"#Idiv1_form #tranumberorder\").val());\r\n");
      out.write("\t\t$(\"#searchForm #traamountmin\").val($(\"#Idiv1_form #traamountmin\").val());\r\n");
      out.write("\t\t$(\"#searchForm #traamountmax\").val($(\"#Idiv1_form #traamountmax\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #traamountorder\").val($(\"#Idiv1_form #traamountorder\").val());\r\n");
      out.write("\t\t$(\"#searchForm #datemin\").datetimebox(\"setValue\",$(\"#Idiv1_form #datemin\").datebox(\"getValue\")); //后台只认可yyyy-MM-dd HH:mm:ss为Date类型\r\n");
      out.write("\t\t$(\"#searchForm #datemax\").datetimebox(\"setValue\",$(\"#Idiv1_form #datemax\").datebox(\"getValue\"));\r\n");
      out.write("\t\t$(\"#searchForm #datenum\").val($(\"#Idiv1_form #datenum\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #dateorder\").val($(\"#Idiv1_form #dateorder\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #difforder\").val($(\"#Idiv1_form #difforder\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #deaorder\").val($(\"#Idiv1_form #deaorder\").val());\r\n");
      out.write("\t\t\t$(\"#searchForm #macdorder\").val($(\"#Idiv1_form #macdorder\").val());\r\n");
      out.write("\t\t$(\"#searchForm #macdmin\").val($(\"#Idiv1_form #macdmin\").val());\r\n");
      out.write("\t\t$(\"#searchForm #macdmax\").val($(\"#Idiv1_form #macdmax\").val());\r\n");
      out.write("    \t$(\"#Idiv1\").dialog('close');\r\n");
      out.write("    }\r\n");
      out.write("    function Idiv1_rest(){\r\n");
      out.write("    \t$(\"#Idiv1_form\")[0].reset();\r\n");
      out.write("    }\r\n");
      out.write("    function restSearch(){\r\n");
      out.write("    \t$(\"#searchForm\")[0].reset();\r\n");
      out.write("    \t$(\"#Idiv1_form\")[0].reset();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("      function findById(c){\r\n");
      out.write("  \t\t   $.ajax({\r\n");
      out.write("                cache: true,\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url:\"");
      out.print(path);
      out.write("/tSearchs/getId.do?id=\"+c,\r\n");
      out.write("                // data:$('#fm').serialize(),你的formid或者 { id: idIndex, name: nameIndex },//提交参数\r\n");
      out.write("                async: false,\r\n");
      out.write("               // dataType : \"json\",设置需要返回的数据类型\r\n");
      out.write("                error: function(request) {\r\n");
      out.write("                    alert(\"操作失败了！\");\r\n");
      out.write("                },\r\n");
      out.write("                //data没有指定json的话默认string\r\n");
      out.write("                success: function(row) {\r\n");
      out.write("                \tvar sflag =row.success;  \r\n");
      out.write("                \tif(row.success){\r\n");
      out.write("                \t\tvar increpermin=row.data.increpermin;\r\n");
      out.write("                \t\tvar increpermax=row.data.increpermax;\r\n");
      out.write("                \t\tvar increperorder=row.data.increperorder;\r\n");
      out.write("                \t\tvar swingmin=row.data.swingmin;\r\n");
      out.write("                \t\tvar swingmax=row.data.swingmax;\r\n");
      out.write("                \t\tvar swingorder=row.data.swingorder;\r\n");
      out.write("                \t\tvar tranumbermin=row.data.tranumbermin;\r\n");
      out.write("                \t\tvar tranumbermax=row.data.tranumbermax;\r\n");
      out.write("                \t\tvar tranumberorder=row.data.tranumberorder;\r\n");
      out.write("                \t\tvar traamountmin=row.data.traamountmin;\r\n");
      out.write("                \t\tvar traamountmax=row.data.traamountmax;\r\n");
      out.write("                \t\tvar traamountorder=row.data.traamountorder;\r\n");
      out.write("                \t\tvar datemin=row.data.datemin;\r\n");
      out.write("                \t\tvar datemax=row.data.datemax;\r\n");
      out.write("                \t\tvar datenum=row.data.datenum;\r\n");
      out.write("                \t\tvar dateorder=row.data.dateorder;\r\n");
      out.write("                \t\tvar difforder=row.data.difforder;\r\n");
      out.write("                \t\tvar deaorder=row.data.deaorder;\r\n");
      out.write("                \t\tvar macdorder=row.data.macdorder;\r\n");
      out.write("                \t\tvar macdmin=row.data.macdmin;\r\n");
      out.write("                \t\tvar macdmax=row.data.macdmax;\r\n");
      out.write("                \t\tvar gtype=row.data.gtype;\r\n");
      out.write("                \t\t\r\n");
      out.write("                \t\tif(!gtype){\r\n");
      out.write("                \t\t\tgtype=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#searchForm #gtype\").val(gtype);\r\n");
      out.write("                \t\tif(!increpermin&&increpermin!=0){\r\n");
      out.write("                \t\t\tincrepermin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #increpermin\").val(increpermin);\r\n");
      out.write("                \t\tif(!increpermax&&increpermax!=0){\r\n");
      out.write("                \t\t\tincrepermax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #increpermax\").val(increpermax);\r\n");
      out.write("                \t\tif(!increperorder){\r\n");
      out.write("                \t\t\tincreperorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #increperorder\").val(increperorder);\r\n");
      out.write("                \t\tif(!swingmin&&swingmin!=0){\r\n");
      out.write("                \t\t\tswingmin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #swingmin\").val(swingmin);\r\n");
      out.write("                \t\tif(!swingmax&&swingmax!=0){\r\n");
      out.write("                \t\t\tswingmax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #swingmax\").val(swingmax);\r\n");
      out.write("                \t\tif(!swingorder){\r\n");
      out.write("                \t\t\tswingorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #swingorder\").val(swingorder);\r\n");
      out.write("                \t\tif(!tranumbermin&&tranumbermin!=0){\r\n");
      out.write("                \t\t\ttranumbermin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #tranumbermin\").val(tranumbermin);\r\n");
      out.write("                \t\tif(!tranumbermax&&tranumbermax!=0){\r\n");
      out.write("                \t\t\ttranumbermax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #tranumbermax\").val(tranumbermax);\r\n");
      out.write("                \t\tif(!tranumberorder){\r\n");
      out.write("                \t\t\ttranumberorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #tranumberorder\").val(tranumberorder);\r\n");
      out.write("                \t\tif(!traamountmin&&traamountmin!=0){\r\n");
      out.write("                \t\t\ttraamountmin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #traamountmin\").val(traamountmin);\r\n");
      out.write("                \t\tif(!traamountmax&&traamountmax!=0){\r\n");
      out.write("                \t\t\ttraamountmax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #traamountmax\").val(traamountmax);\r\n");
      out.write("                \t\tif(!traamountorder){\r\n");
      out.write("                \t\t\ttraamountorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #traamountorder\").val(traamountorder);\r\n");
      out.write("                \t\tif(!datemin){\r\n");
      out.write("                \t\t\tdatemin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #datemin\").datebox(\"setValue\",datemin);\r\n");
      out.write("                \t\tif(!datemax){\r\n");
      out.write("                \t\t\tdatemax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #datemax\").datebox(\"setValue\",datemin);\r\n");
      out.write("                \t\tif(!datenum&&datenum!=0){\r\n");
      out.write("                \t\t\tdatenum=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #datenum\").val(datenum);\r\n");
      out.write("                \t\tif(!dateorder){\r\n");
      out.write("                \t\t\tdateorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #dateorder\").val(dateorder);\r\n");
      out.write("                \t\tif(!difforder){\r\n");
      out.write("                \t\t\tdifforder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #difforder\").val(difforder);\r\n");
      out.write("                \t\tif(!deaorder){\r\n");
      out.write("                \t\t\tdeaorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #deaorder\").val(deaorder);\r\n");
      out.write("                \t\tif(!macdorder){\r\n");
      out.write("                \t\t\tmacdorder=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #macdorder\").val(macdorder);\r\n");
      out.write("                \t\tif(!macdmin&&macdmin!=0){\r\n");
      out.write("                \t\t\tmacdmin=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #macdmin\").val(macdmin);\r\n");
      out.write("                \t\tif(!macdmax&&macdmax!=0){\r\n");
      out.write("                \t\t\tmacdmax=\"\";\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t$(\"#Idiv1_form #macdmax\").val(macdmax);\r\n");
      out.write("                \t}\r\n");
      out.write("                \t//var dataJson = eval(\"(\" + data + \")\");  \r\n");
      out.write("                }\r\n");
      out.write("   \t\t  });\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"easyui-layout\">\r\n");
      out.write(" \t <!-- Search panel start -->\r\n");
      out.write(" \t <div class=\"ui-search-panel\" region=\"north\" style=\"height: 80px;\" title=\"过滤条件\" data-options=\"striped: true,collapsible:false,iconCls:'icon-search',border:false\" >  \r\n");
      out.write(" \t <div style=\"float:left\">\r\n");
      out.write(" \t <form id=\"searchForm\">\r\n");
      out.write("        <p class=\"ui-fields\">\r\n");
      out.write("\t\t\t<label class=\"ui-label\">大盘类型:</label>\r\n");
      out.write("\t\t\t<select name=\"gtype\">\r\n");
      out.write("\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t<option value=\"1\">上证指数</option>\r\n");
      out.write("\t\t\t<option value=\"2\">深证指数</option>\r\n");
      out.write("\t\t\t<option value=\"3\">创业板指数</option>\r\n");
      out.write("\t\t\t</select>&emsp;\r\n");
      out.write("\t\t\t<input name=\"datemin\" id=\"datemin\" class=\"easyui-datetimebox\" type=\"hidden\">&emsp;\r\n");
      out.write("\t\t\t<a href=\"#\" onclick=\"IdivOpen(1,1)\">更多</a>&emsp;\r\n");
      out.write("\t\t\t<input name=\"increpermin\" id=\"increpermin\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"increpermax\" id=\"increpermax\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"increperorder\" id=\"increperorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"swingmin\" id=\"swingmin\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"swingmax\" id=\"swingmax\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"swingorder\" id=\"swingorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"tranumbermin\" id=\"tranumbermin\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"tranumbermax\" id=\"tranumbermax\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"tranumberorder\" id=\"tranumberorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"traamountmin\" id=\"traamountmin\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"traamountmax\" id=\"traamountmax\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"traamountorder\" id=\"traamountorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"datemax\" id=\"datemax\" class=\"easyui-datetimebox\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"datenum\" id=\"datenum\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"dateorder\" id=\"dateorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"difforder\" id=\"difforder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"deaorder\" id=\"deaorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"macdorder\" id=\"macdorder\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"macdmin\" id=\"macdmin\" type=\"hidden\">\r\n");
      out.write("\t\t  \t<input name=\"macdmax\" id=\"macdmax\" type=\"hidden\">\r\n");
      out.write("\t    </p>\r\n");
      out.write("\t    <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>&emsp;\r\n");
      out.write("      </form>\r\n");
      out.write("     </div>\r\n");
      out.write("      <div style=\"float:left\">\r\n");
      out.write("      <a href=\"#\"  class=\"easyui-linkbutton\" onclick=\"restSearch()\">重置</a>&emsp;\r\n");
      out.write("      <a href=\"http://finance.sina.com.cn/realstock/company/sh000001/nc.shtml\" target=\"_blank\" class=\"easyui-linkbutton\">上证新浪链接</a>&emsp;\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"float:right\">\r\n");
      out.write("      <a href=\"#\" id=\"btn-search\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"backBigDate('0')\">自动加最新大盘日K</a>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div> \r\n");
      out.write("     <!--  Search panel end -->\r\n");
      out.write("\r\n");
      out.write("     <!-- Data List -->\r\n");
      out.write("     <div region=\"center\" border=\"false\" >\r\n");
      out.write("     <table id=\"data-list\"></table>\r\n");
      out.write("\t </div>\r\n");
      out.write("  \t \r\n");
      out.write("  \t   <!--弹出层开始单选-->\r\n");
      out.write("\t\t<div id=\"Idiv1\" class=\"easyui-dialog\" title=\"更多查询条件\" data-options=\"closed:true,iconCls:'icon-save',modal:true\" style=\"width:840px;height:450px;\">\r\n");
      out.write("\t\t\t<div id=\"Idiv1_1\" style=\"margin:10px;\">\r\n");
      out.write("\t\t\t<form id=\"Idiv1_form\">\r\n");
      out.write("\t\t\t\t<table id=\"Idiv1_table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t  <td colspan=\"4\"><label class=\"ui-label\">已有查询条件选择:</label>\r\n");
      out.write("\t\t\t\t  <input class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t\t\t    valueField: 'id',\r\n");
      out.write("\t\t\t\t    textField: 'searchtitle',\r\n");
      out.write("\t\t\t\t    url: '");
      out.print(path);
      out.write("/tSearchs/queryAll.do?typeflag=1',\r\n");
      out.write("\t\t\t\t    onSelect: function(rec){\r\n");
      out.write("\t\t\t\t \t  \t findById(rec.id);\r\n");
      out.write("\t\t\t\t    }\" style=\"width:570px;\">\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">涨幅:</label><input name=\"increpermin\"  id=\"increpermin\" class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:50px;\">%\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"increpermax\" id=\"increpermax\" class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:50px;\">%\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">涨幅排序:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"increperorder\" id=\"increperorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><label class=\"ui-label\">振幅:</label><input name=\"swingmin\" id=\"swingmin\" class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:50px;\">%\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"swingmax\" id=\"swingmax\" class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:50px;\">%</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">振幅排序:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"swingorder\" id=\"swingorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">成交量/手:</label><input name=\"tranumbermin\"  id=\"tranumbermin\" class=\"easyui-numberbox\" data-options=\"precision:0\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"tranumbermax\" id=\"tranumbermax\" class=\"easyui-numberbox\" data-options=\"precision:0\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">成交量排序:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"tranumberorder\" id=\"tranumberorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">成交金额/万:</label><input name=\"traamountmin\" id=\"traamountmin\" class=\"easyui-numberbox\" data-options=\"precision:0\" style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"traamountmax\" id=\"traamountmax\" class=\"easyui-numberbox\" data-options=\"precision:0\" style=\"width:50px;\"></td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">成交金额排序:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"traamountorder\" id=\"traamountorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">diff连续升降:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"difforder\" id=\"difforder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">dea连续升降:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"deaorder\" id=\"deaorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t  \t<td>\r\n");
      out.write("\t\t\t\t  \t<label class=\"ui-label\">macd:</label><input name=\"macdmin\"  id=\"macdmin\"  class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:40px;\">\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"macdmax\" id=\"macdmax\" class=\"easyui-numberbox\" data-options=\"precision:1\" style=\"width:40px;\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"macdorder\" id=\"macdorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><label class=\"ui-label\">最近几天数据:</label><input name=\"datenum\" id=\"datenum\" class=\"easyui-numberbox\" data-options=\"precision:0\" style=\"width:50px;\">天</td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t  \t<td colspan=\"2\"><label class=\"ui-label\">日期:</label><input name=\"datemin\"  id=\"datemin\" class=\"easyui-datebox\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t  \t—&nbsp;<input name=\"datemax\" id=\"datemax\" class=\"easyui-datebox\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t  \t<td><label class=\"ui-label\">日期排序:</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"dateorder\" id=\"dateorder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">升序</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">降序</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t  <tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t  \t<td colspan=\"4\"><font color=\"red\">注意：1，</font>当用到最近几天升降则用不到日期范围了,特别是最小日期。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">2，</font>没有diff,dea,macd查询时的排序顺序为：日期，涨幅，换手率，振幅，成交量，成交金额。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">3，</font>当有diff,dea,macd查询时的排序顺序为：股票代码升序，日期降序（因为第一条数据放到新的list），涨幅，换手率，振幅，成交量，成交金额。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">4，</font>当有diff,dea,macd查询时,最近几天数据是必填的（不填日期范围太大）且大于1（1天没法跟自己比较）否则他们的条件没用其他有用。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">5，</font>当有diff,dea,macd查询时,建议用更大的翻页数值，因为按照gcode排序，查到最后一条要3000*datenum左右（3天就1W翻页，10天就3W左右翻页），最好查到全部，这样更准确。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">6，</font>如果前一日的diff,dea,macd与后一日的diff,dea,macd相等我们算正确的，毕竟这种概率也很小。\r\n");
      out.write("\t\t\t\t  \t<font color=\"red\">7，</font>大盘类型少，查所有\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t  <!--结束-->\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("  \t <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/view/stocks/datas/page-tDayBigdata.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
